"""Controlled finite multistream collection and exact static decisions.

The module composes the repaired scalar Bernoulli receiver.  It checks a fixed
registry, an append-only transcript generated by one of a few built-in rules,
rowwise outward interval evidence, and affine risks on the retained rectangle.
It does not validate physical sampling premises or execute submitted code.
"""
from dataclasses import asdict, dataclass
from fractions import Fraction as F
from pathlib import Path
import hashlib
import json
import re
import sys


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from verification.statistical_decision_bridge import reference as scalar  # noqa: E402


JOINT_PREMISE = "each-complete-row-iid-bernoulli-one-fixed-real-parameter"
CROSS_STREAM_UNRESTRICTED = "cross-stream-dependence-unrestricted-subject-to-row-premises"
CROSS_STREAM_INDEPENDENT = "mutually-independent-complete-stream-rows"
FRESH_DRAW_PREMISE = "fresh-population-draw-independent-of-observed-history-given-parameters"
POPULATION_RISK = "affine-population-expected-risk"
CONDITIONAL_FRESH_DRAW_RISK = "affine-conditional-fresh-draw-risk"
DECISION_QUERY = "exact-affine-risk-on-retained-parameter-rectangle"
COLLECTION_CLAIM = "checked-built-in-rule-and-complete-prefix-transcript"
COVERAGE_CLAIM = "all-stream-all-prefix-outward-rectangle"
DECISION_CLAIM = "exact-static-affine-decision-on-retained-rectangle"

RULE_ROUND_ROBIN_BUDGET = "round-robin-to-registry-budget"
RULE_ROUND_ROBIN_SIX = "round-robin-stop-at-6"
RULE_ROUND_ROBIN_EIGHT = "round-robin-stop-at-8"
RULE_SWITCH_AFTER_ONE = "switch-after-1-gap-half-or-12"
SUPPORTED_RULES = {
    RULE_ROUND_ROBIN_BUDGET,
    RULE_ROUND_ROBIN_SIX,
    RULE_ROUND_ROBIN_EIGHT,
    RULE_SWITCH_AFTER_ONE,
}

MAX_STREAMS = 4
MAX_OBSERVATIONS_PER_STREAM = scalar.MAX_N
MAX_ACTIONS = 4
MAX_PRECISION_BITS = scalar.MAX_PRECISION_BITS
MAX_TRANSCRIPT = MAX_STREAMS * MAX_OBSERVATIONS_PER_STREAM


Invalid = scalar.Invalid


def need(ok, message):
    if not ok:
        raise Invalid(message)


def identity(value, message="nonempty identity required"):
    need(type(value) is str and bool(value), message)
    return value


def strict_integer(value, message="strict integer required"):
    need(type(value) is int, message)
    return value


def exact(value, message="exact Fraction proof coordinate required"):
    need(type(value) is F, message)
    return value


def digest_payload(payload):
    return hashlib.sha256(json.dumps(payload, sort_keys=True,
                                     separators=(",", ":")).encode()).hexdigest()


def resource_refusal(reason, limit, requested):
    return {"status": "unfinished", "kind": "resource-refusal",
            "reason": reason, "limit": limit, "requested": requested}


@dataclass(frozen=True)
class StreamSpec:
    stream_identity: str
    population_identity: str
    protocol_identity: str
    premise: str = scalar.IID_PREMISE

    def validate(self):
        identity(self.stream_identity, "nonempty stream identity required")
        identity(self.population_identity, "nonempty population identity required")
        identity(self.protocol_identity, "nonempty protocol identity required")
        need(self.premise == scalar.IID_PREMISE, "unsupported within-stream premise")
        return self


def make_stream(stream, population, protocol, premise=scalar.IID_PREMISE):
    return StreamSpec(stream, population, protocol, premise).validate()


@dataclass(frozen=True)
class Observation:
    global_index: int
    stream_identity: str
    local_index: int
    value: int
    event_identity: str

    def validate(self):
        strict_integer(self.global_index, "strict global index required")
        strict_integer(self.local_index, "strict local index required")
        need(self.global_index >= 1 and self.local_index >= 1,
             "positive transcript indices required")
        identity(self.stream_identity, "nonempty observed stream identity required")
        identity(self.event_identity, "nonempty event identity required")
        need(type(self.value) is int and self.value in (0, 1),
             "binary observation required")
        return self


def make_observation(global_index, stream, local_index, value, event_identity):
    return Observation(global_index, stream, local_index, value,
                       event_identity).validate()


@dataclass(frozen=True)
class CollectionRequest:
    registry: tuple
    total_alpha: F
    allocations: tuple
    precision_bits: int
    rule_identity: str
    transcript: tuple
    stopped: bool
    record_identity: str
    revision_identity: str
    predecessor_digest: object
    joint_premise: str = JOINT_PREMISE
    cross_stream_premise: str = CROSS_STREAM_UNRESTRICTED

    def __post_init__(self):
        object.__setattr__(self, "registry", tuple(self.registry))
        object.__setattr__(self, "allocations",
                           tuple(tuple(row) for row in self.allocations))
        object.__setattr__(self, "transcript", tuple(self.transcript))

    def validate(self):
        need(bool(self.registry) and all(type(item) is StreamSpec for item in self.registry),
             "nonempty stream registry required")
        for item in self.registry:
            item.validate()
        stream_ids = tuple(item.stream_identity for item in self.registry)
        need(len(set(stream_ids)) == len(stream_ids), "duplicate registered stream")
        need(type(self.total_alpha) is F and 0 < self.total_alpha < 1,
             "exact total alpha in (0,1) required")
        scalar.rational(self.total_alpha)
        need(len(self.allocations) == len(self.registry),
             "one stream allocation per registered stream required")
        allocation_ids = []
        allocation_sum = F(0)
        for row in self.allocations:
            need(len(row) == 2, "stream allocation pair required")
            stream, alpha = row
            identity(stream, "allocation stream identity required")
            need(type(alpha) is F and alpha > 0, "positive exact stream allocation required")
            scalar.rational(alpha)
            allocation_ids.append(stream)
            allocation_sum += alpha
        need(len(set(allocation_ids)) == len(allocation_ids),
             "duplicate stream allocation")
        need(set(allocation_ids) == set(stream_ids),
             "allocation registry mismatch")
        need(allocation_sum <= self.total_alpha, "stream allocations exceed total alpha")
        strict_integer(self.precision_bits, "strict integer precision required")
        need(self.precision_bits >= 0, "nonnegative precision required")
        need(self.rule_identity in SUPPORTED_RULES, "unsupported collection rule")
        if self.rule_identity == RULE_SWITCH_AFTER_ONE:
            need(len(self.registry) == 2,
                 "switch-after-one rule requires exactly two registered streams")
        need(all(type(event) is Observation for event in self.transcript),
             "typed transcript observations required")
        for event in self.transcript:
            event.validate()
            need(event.stream_identity in stream_ids, "unregistered observed stream")
        need(type(self.stopped) is bool, "stopping status required")
        identity(self.record_identity, "nonempty collection record identity required")
        identity(self.revision_identity, "nonempty collection revision identity required")
        need(self.predecessor_digest is None or
             (type(self.predecessor_digest) is str and
              re.fullmatch(r"[0-9a-f]{64}", self.predecessor_digest) is not None),
             "predecessor digest must be absent or SHA-256")
        need(self.joint_premise == JOINT_PREMISE, "unsupported joint sampling premise")
        need(self.cross_stream_premise in
             (CROSS_STREAM_UNRESTRICTED, CROSS_STREAM_INDEPENDENT),
             "unsupported cross-stream premise")
        return self


def make_collection(registry, total_alpha, allocations, *, precision_bits=16,
                    rule=RULE_ROUND_ROBIN_BUDGET, transcript=(), stopped=False,
                    record="collection-1", revision="revision-1",
                    predecessor_digest=None, joint_premise=JOINT_PREMISE,
                    cross_stream_premise=CROSS_STREAM_UNRESTRICTED):
    registry = tuple(registry)
    allocations = tuple(allocations)
    stream_ids = tuple(item.stream_identity for item in registry)
    normalized_allocations = []
    for row in allocations:
        need(type(row) in (tuple, list) and len(row) == 2,
             "stream allocation pair required")
        stream, alpha = row
        identity(stream, "allocation stream identity required")
        normalized_allocations.append((stream, scalar.rational(alpha)))
    allocation_map = dict(normalized_allocations)
    need(len(allocation_map) == len(allocations), "duplicate stream allocation")
    need(set(allocation_map) == set(stream_ids), "allocation registry mismatch")
    canonical_allocations = tuple((stream, allocation_map[stream]) for stream in stream_ids)
    request = CollectionRequest(
        registry, scalar.rational(total_alpha), canonical_allocations,
        precision_bits, rule, tuple(transcript), stopped, record, revision,
        predecessor_digest, joint_premise, cross_stream_premise)
    return request.validate()


def collection_payload(request):
    request.validate()
    allocations = dict(request.allocations)
    return {
        "registry": tuple((item.stream_identity, item.population_identity,
                           item.protocol_identity, item.premise)
                          for item in request.registry),
        "total_alpha": str(request.total_alpha),
        "allocations": tuple((item.stream_identity,
                              str(allocations[item.stream_identity]))
                             for item in request.registry),
        "precision_bits": request.precision_bits,
        "rule_identity": request.rule_identity,
        "transcript": tuple((event.global_index, event.stream_identity,
                             event.local_index, event.value,
                             event.event_identity)
                            for event in request.transcript),
        "stopped": request.stopped,
        "record_identity": request.record_identity,
        "revision_identity": request.revision_identity,
        "predecessor_digest": request.predecessor_digest,
        "joint_premise": request.joint_premise,
        "cross_stream_premise": request.cross_stream_premise,
    }


def collection_digest(request):
    return digest_payload(collection_payload(request))


def _raw_counts(request):
    counts = {item.stream_identity: 0 for item in request.registry}
    for event in request.transcript:
        counts[event.stream_identity] += 1
    return counts


def collection_budget(request):
    request.validate()
    if len(request.registry) > MAX_STREAMS:
        return resource_refusal("stream-count-limit", MAX_STREAMS,
                                len(request.registry))
    if len(request.transcript) > MAX_TRANSCRIPT:
        return resource_refusal("transcript-length-limit", MAX_TRANSCRIPT,
                                len(request.transcript))
    counts = _raw_counts(request)
    largest = max(counts.values(), default=0)
    if largest > MAX_OBSERVATIONS_PER_STREAM:
        return resource_refusal("per-stream-observation-limit",
                                MAX_OBSERVATIONS_PER_STREAM, largest)
    if request.precision_bits > MAX_PRECISION_BITS:
        return resource_refusal("precision-request-limit", MAX_PRECISION_BITS,
                                request.precision_bits)
    return None


def _means(prefixes):
    return {stream: F(sum(values), len(values)) if values else None
            for stream, values in prefixes.items()}


def rule_directive(request, prefixes, history):
    """Return (disposition, next_stream) for a built-in nonanticipative rule."""
    request.validate()
    stream_ids = tuple(item.stream_identity for item in request.registry)
    t = len(history)
    counts = {stream: len(prefixes[stream]) for stream in stream_ids}
    if request.rule_identity == RULE_ROUND_ROBIN_BUDGET:
        if all(count == MAX_OBSERVATIONS_PER_STREAM for count in counts.values()):
            return "stop", None
        return "observe", stream_ids[t % len(stream_ids)]
    if request.rule_identity in (RULE_ROUND_ROBIN_SIX, RULE_ROUND_ROBIN_EIGHT):
        horizon = 6 if request.rule_identity == RULE_ROUND_ROBIN_SIX else 8
        if t == horizon:
            return "stop", None
        return "observe", stream_ids[t % len(stream_ids)]
    need(request.rule_identity == RULE_SWITCH_AFTER_ONE,
         "unsupported collection rule")
    if t == 12:
        return "stop", None
    if all(counts[stream] >= 2 for stream in stream_ids):
        means = _means(prefixes)
        if abs(means[stream_ids[0]] - means[stream_ids[1]]) > F(1, 2):
            return "stop", None
    if not history:
        return "observe", stream_ids[0]
    last = history[-1]
    if last.value == 0:
        return "observe", last.stream_identity
    return "observe", next(stream for stream in stream_ids
                           if stream != last.stream_identity)


def replay_transcript(request):
    request.validate()
    prefixes = {item.stream_identity: () for item in request.registry}
    seen_events = set()
    history = []
    for position, event in enumerate(request.transcript, 1):
        disposition, selected = rule_directive(request, prefixes, tuple(history))
        need(disposition == "observe", "observation recorded after rule stopped")
        need(event.global_index == position, "global transcript index mismatch")
        need(event.stream_identity == selected, "transcript violates collection rule")
        expected_local = len(prefixes[selected]) + 1
        need(event.local_index == expected_local,
             "omitted, duplicated or out-of-order local observation")
        need(event.event_identity not in seen_events, "duplicated physical event identity")
        seen_events.add(event.event_identity)
        prefixes[selected] += (event.value,)
        history.append(event)
    disposition, next_stream = rule_directive(request, prefixes, tuple(history))
    need(request.stopped == (disposition == "stop"),
         "mismatched stopping status or rule")
    return {
        "prefixes": tuple((item.stream_identity, prefixes[item.stream_identity])
                          for item in request.registry),
        "counts": tuple((item.stream_identity,
                         len(prefixes[item.stream_identity]))
                        for item in request.registry),
        "disposition": disposition,
        "next_stream": next_stream,
        "transcript_length": len(history),
    }


@dataclass(frozen=True)
class CollectionEvidence:
    subject: CollectionRequest
    prefixes: tuple
    counts: tuple
    disposition: str
    next_stream: object
    transcript_digest: str
    subject_digest: str
    claim: str = COLLECTION_CLAIM

    def __post_init__(self):
        object.__setattr__(self, "prefixes",
                           tuple((stream, tuple(values)) for stream, values in self.prefixes))
        object.__setattr__(self, "counts", tuple(tuple(row) for row in self.counts))


def produce_collection(request):
    request.validate()
    refusal = collection_budget(request)
    if refusal:
        return refusal
    replayed = replay_transcript(request)
    digest = collection_digest(request)
    return CollectionEvidence(
        request, replayed["prefixes"], replayed["counts"],
        replayed["disposition"], replayed["next_stream"],
        digest_payload(collection_payload(request)["transcript"]), digest)


def consume_collection(expected, evidence):
    """Replay the built-in rule and compare every transcript-derived field."""
    expected.validate()
    refusal = collection_budget(expected)
    if refusal:
        return refusal
    need(type(evidence) is CollectionEvidence, "collection evidence required")
    need(type(evidence.subject) is CollectionRequest, "collection subject required")
    evidence.subject.validate()
    need(evidence.subject == expected, "collection subject mismatch")
    need(evidence.claim == COLLECTION_CLAIM, "unsupported collection claim")
    expected_digest = collection_digest(expected)
    need(evidence.subject_digest == expected_digest, "collection digest mismatch")
    replayed = replay_transcript(expected)
    need(evidence.prefixes == replayed["prefixes"], "false collected prefixes")
    need(evidence.counts == replayed["counts"], "false local counts")
    need(evidence.disposition == replayed["disposition"],
         "false stopping disposition")
    need(evidence.next_stream == replayed["next_stream"],
         "false next-stream claim")
    transcript_digest = digest_payload(collection_payload(expected)["transcript"])
    need(evidence.transcript_digest == transcript_digest,
         "transcript digest mismatch")
    return {
        "status": "checked-collection-transcript",
        **replayed,
        "record_identity": expected.record_identity,
        "revision_identity": expected.revision_identity,
        "subject_digest": expected_digest,
        "premises_checked_as_inputs_not_empirically_validated": True,
    }


def scalar_request(request, stream_identity, observations):
    """Project one checked collection row into the repaired scalar contract."""
    request.validate()
    specifications = {item.stream_identity: item for item in request.registry}
    allocations = dict(request.allocations)
    need(stream_identity in specifications, "unknown scalar projection stream")
    spec = specifications[stream_identity]
    return scalar.make_sampling(
        observations, allocations[stream_identity], stream=spec.stream_identity,
        population=spec.population_identity, protocol=spec.protocol_identity,
        premise=spec.premise, precision_bits=request.precision_bits)


@dataclass(frozen=True)
class CoverageEvidence:
    subject: CollectionRequest
    collection_evidence: CollectionEvidence
    scalar_evidence: tuple
    rectangle: tuple
    allocation_sum: F
    simultaneous_coverage_lower: F
    total_alpha_coverage_lower: F
    subject_digest: str
    claim: str = COVERAGE_CLAIM

    def __post_init__(self):
        object.__setattr__(self, "scalar_evidence", tuple(tuple(row)
                                                          for row in self.scalar_evidence))
        object.__setattr__(self, "rectangle", tuple(tuple(row)
                                                     for row in self.rectangle))


def produce_coverage(request, collection_evidence):
    request.validate()
    refusal = collection_budget(request)
    if refusal:
        return refusal
    checked = consume_collection(request, collection_evidence)
    if checked.get("status") == "unfinished":
        return checked
    prefixes = dict(checked["prefixes"])
    rows = []
    rectangle = []
    for spec in request.registry:
        projected = scalar_request(request, spec.stream_identity,
                                   prefixes[spec.stream_identity])
        evidence = scalar.produce_interval(projected)
        need(type(evidence) is scalar.IntervalEvidence,
             "bounded scalar producer unexpectedly unfinished")
        rows.append((spec.stream_identity, evidence))
        rectangle.append((spec.stream_identity, *evidence.outward_interval))
    allocation_sum = sum((alpha for _, alpha in request.allocations), F(0))
    return CoverageEvidence(
        request, collection_evidence, tuple(rows), tuple(rectangle),
        allocation_sum, 1 - allocation_sum, 1 - request.total_alpha,
        collection_digest(request))


def consume_coverage(expected, evidence):
    """Check each row independently, then apply only the finite union bound."""
    expected.validate()
    refusal = collection_budget(expected)
    if refusal:
        return refusal
    need(type(evidence) is CoverageEvidence, "coverage evidence required")
    need(type(evidence.subject) is CollectionRequest, "coverage subject required")
    evidence.subject.validate()
    need(evidence.subject == expected, "coverage subject mismatch")
    need(evidence.claim == COVERAGE_CLAIM, "unsupported coverage claim")
    need(evidence.subject_digest == collection_digest(expected),
         "coverage digest mismatch")
    collected = consume_collection(expected, evidence.collection_evidence)
    if collected.get("status") == "unfinished":
        return collected
    stream_ids = tuple(item.stream_identity for item in expected.registry)
    need(len(evidence.scalar_evidence) == len(stream_ids),
         "missing scalar evidence row")
    scalar_rows = {}
    for row in evidence.scalar_evidence:
        need(len(row) == 2 and type(row[0]) is str,
             "identified scalar evidence row required")
        need(row[0] not in scalar_rows, "duplicate scalar evidence row")
        scalar_rows[row[0]] = row[1]
    need(set(scalar_rows) == set(stream_ids), "scalar evidence registry mismatch")
    prefixes = dict(collected["prefixes"])
    expected_rectangle = []
    scalar_statuses = []
    for stream in stream_ids:
        projected = scalar_request(expected, stream, prefixes[stream])
        checked = scalar.consume_interval(projected, scalar_rows[stream])
        if checked.get("status") == "unfinished":
            return checked
        expected_rectangle.append((stream, *checked["outward_interval"]))
        scalar_statuses.append((stream, checked["status"]))
    need(evidence.rectangle == tuple(expected_rectangle),
         "false or reordered retained rectangle")
    allocation_sum = sum((alpha for _, alpha in expected.allocations), F(0))
    need(type(evidence.allocation_sum) is F and
         evidence.allocation_sum == allocation_sum,
         "false stream-allocation sum")
    need(type(evidence.simultaneous_coverage_lower) is F and
         evidence.simultaneous_coverage_lower == 1 - allocation_sum,
         "false simultaneous-coverage bound")
    need(type(evidence.total_alpha_coverage_lower) is F and
         evidence.total_alpha_coverage_lower == 1 - expected.total_alpha,
         "false total-alpha coverage bound")
    return {
        "status": "checked-multistream-coverage",
        "rectangle": tuple(expected_rectangle),
        "allocation_sum": allocation_sum,
        "simultaneous_coverage_lower": 1 - allocation_sum,
        "total_alpha_coverage_lower": 1 - expected.total_alpha,
        "cross_stream_independence_used": False,
        "random_local_counts_conditioned_on": False,
        "rowwise_all_prefix_events_evaluated_at_realized_counts": True,
        "scalar_statuses": tuple(scalar_statuses),
    }


@dataclass(frozen=True)
class AffineAction:
    label: str
    intercept: F
    weights: tuple

    def __post_init__(self):
        object.__setattr__(self, "weights", tuple(tuple(row) for row in self.weights))

    def validate(self):
        identity(self.label, "nonempty action label required")
        exact(self.intercept, "exact affine intercept required")
        scalar.rational(self.intercept)
        ids = []
        for row in self.weights:
            need(len(row) == 2, "stream-weight pair required")
            stream, weight = row
            identity(stream, "weight stream identity required")
            need(type(weight) is F, "exact affine weight required")
            scalar.rational(weight)
            ids.append(stream)
        need(len(set(ids)) == len(ids), "duplicate affine weight")
        return self


def make_affine_action(label, intercept, weights):
    weights = tuple(weights.items()) if type(weights) is dict else tuple(weights)
    return AffineAction(label, scalar.rational(intercept),
                        tuple((stream, scalar.rational(weight))
                              for stream, weight in weights)).validate()


@dataclass(frozen=True)
class DecisionRequest:
    collection: CollectionRequest
    actions: tuple
    loss_unit: str
    intended_action: str
    regret_cap: object = None
    risk_scope: str = POPULATION_RISK
    fresh_draw_premise: object = None
    query: str = DECISION_QUERY

    def __post_init__(self):
        object.__setattr__(self, "actions", tuple(self.actions))

    def validate(self):
        need(type(self.collection) is CollectionRequest,
             "collection request required")
        self.collection.validate()
        identity(self.loss_unit, "nonempty loss unit required")
        need(self.query == DECISION_QUERY, "unsupported decision query")
        need(bool(self.actions) and
             all(type(action) is AffineAction for action in self.actions),
             "nonempty exact affine action table required")
        stream_ids = tuple(item.stream_identity for item in self.collection.registry)
        labels = []
        for action in self.actions:
            action.validate()
            need(set(stream for stream, _ in action.weights) == set(stream_ids) and
                 len(action.weights) == len(stream_ids),
                 "affine action weight registry mismatch")
            labels.append(action.label)
        need(len(set(labels)) == len(labels), "duplicate action label")
        need(type(self.intended_action) is str and self.intended_action in labels,
             "independently intended action required")
        if self.regret_cap is not None:
            need(type(self.regret_cap) is F and self.regret_cap >= 0,
                 "nonnegative exact regret cap required")
            scalar.rational(self.regret_cap)
        need(self.risk_scope in (POPULATION_RISK, CONDITIONAL_FRESH_DRAW_RISK),
             "unsupported risk scope")
        if self.risk_scope == CONDITIONAL_FRESH_DRAW_RISK:
            need(self.fresh_draw_premise == FRESH_DRAW_PREMISE,
                 "conditional fresh-draw risk requires the fixed premise")
        else:
            need(self.fresh_draw_premise is None,
                 "population risk does not accept a fresh-draw premise")
        return self


def make_decision(collection, actions, *, unit="loss", intended_action,
                  regret_cap=None, risk_scope=POPULATION_RISK,
                  fresh_draw_premise=None, query=DECISION_QUERY):
    collection.validate()
    stream_ids = tuple(item.stream_identity for item in collection.registry)
    normalized = []
    for raw in actions:
        action = raw if type(raw) is AffineAction else make_affine_action(*raw)
        action.validate()
        weights = dict(action.weights)
        need(set(weights) == set(stream_ids) and len(weights) == len(stream_ids),
             "affine action weight registry mismatch")
        canonical = AffineAction(action.label, action.intercept,
                                 tuple((stream, weights[stream])
                                       for stream in stream_ids))
        normalized.append(canonical)
    cap = None if regret_cap is None else scalar.rational(regret_cap)
    return DecisionRequest(collection, tuple(normalized), unit, intended_action,
                           cap, risk_scope, fresh_draw_premise, query).validate()


def decision_budget(request):
    request.validate()
    prior = collection_budget(request.collection)
    if prior:
        return prior
    if len(request.actions) > MAX_ACTIONS:
        return resource_refusal("action-count-limit", MAX_ACTIONS,
                                len(request.actions))
    return None


def decision_payload(request):
    request.validate()
    return {
        "collection": collection_digest(request.collection),
        "actions": tuple((action.label, str(action.intercept),
                          tuple((stream, str(weight))
                                for stream, weight in action.weights))
                         for action in request.actions),
        "loss_unit": request.loss_unit,
        "intended_action": request.intended_action,
        "regret_cap": None if request.regret_cap is None else str(request.regret_cap),
        "risk_scope": request.risk_scope,
        "fresh_draw_premise": request.fresh_draw_premise,
        "query": request.query,
    }


def decision_digest(request):
    return digest_payload(decision_payload(request))


def affine_risk(action, parameters):
    action.validate()
    return action.intercept + sum((weight * parameters[stream]
                                   for stream, weight in action.weights), F(0))


def pairwise_box_extreme(request, rectangle, first, second):
    """Maximize R_first-R_second by the sign of each exact coefficient."""
    request.validate()
    actions = {action.label: action for action in request.actions}
    need(first in actions and second in actions, "unknown action comparison")
    bounds = {stream: (lower, upper) for stream, lower, upper in rectangle}
    need(set(bounds) == {item.stream_identity for item in request.collection.registry},
         "rectangle registry mismatch")
    first_action, second_action = actions[first], actions[second]
    first_weights, second_weights = (dict(first_action.weights),
                                     dict(second_action.weights))
    value = first_action.intercept - second_action.intercept
    witness = []
    for spec in request.collection.registry:
        stream = spec.stream_identity
        lower, upper = bounds[stream]
        exact(lower); exact(upper)
        need(0 <= lower <= upper <= 1, "invalid probability rectangle")
        coefficient = first_weights[stream] - second_weights[stream]
        endpoint = upper if coefficient >= 0 else lower
        value += coefficient * endpoint
        witness.append((stream, endpoint))
    return value, tuple(witness)


def _decision_values(request, rectangle):
    labels = tuple(action.label for action in request.actions)
    rows = tuple((first, second, *pairwise_box_extreme(
                    request, rectangle, first, second))
                 for first in labels for second in labels)
    values = {(first, second): value for first, second, value, _ in rows}
    common = tuple(first for first in labels
                   if all(values[first, second] <= 0 for second in labels))
    strict = tuple(first for first in labels
                   if all(values[first, second] < 0
                          for second in labels if second != first))
    intended = request.intended_action
    regret = max(values[intended, second] for second in labels)
    need(regret >= 0, "self-comparison must make regret nonnegative")
    margins = tuple((first, min((-values[first, second]
                                for second in labels if second != first),
                               default=None)) for first in labels)
    return rows, common, strict, regret, margins


@dataclass(frozen=True)
class DecisionEvidence:
    subject: DecisionRequest
    coverage_evidence: CoverageEvidence
    pairwise_extrema: tuple
    common_minimizers: tuple
    uniformly_strict_actions: tuple
    strict_advantage_margins: tuple
    named_action: str
    named_action_regret: F
    regret_cap_met: object
    subject_digest: str
    claim: str = DECISION_CLAIM

    def __post_init__(self):
        object.__setattr__(self, "pairwise_extrema", tuple(tuple(row)
                                                           for row in self.pairwise_extrema))
        object.__setattr__(self, "common_minimizers", tuple(self.common_minimizers))
        object.__setattr__(self, "uniformly_strict_actions",
                           tuple(self.uniformly_strict_actions))
        object.__setattr__(self, "strict_advantage_margins",
                           tuple(tuple(row) for row in self.strict_advantage_margins))


def produce_decision(request, coverage_evidence):
    request.validate()
    refusal = decision_budget(request)
    if refusal:
        return refusal
    checked = consume_coverage(request.collection, coverage_evidence)
    if checked.get("status") == "unfinished":
        return checked
    rows, common, strict, regret, margins = _decision_values(
        request, checked["rectangle"])
    cap_met = None if request.regret_cap is None else regret <= request.regret_cap
    return DecisionEvidence(request, coverage_evidence, rows, common, strict,
                            margins, request.intended_action, regret, cap_met,
                            decision_digest(request))


def consume_decision(expected, evidence):
    """Recompute the rectangle and every affine endpoint extremum exactly."""
    expected.validate()
    refusal = decision_budget(expected)
    if refusal:
        return refusal
    need(type(evidence) is DecisionEvidence, "decision evidence required")
    need(type(evidence.subject) is DecisionRequest, "decision subject required")
    evidence.subject.validate()
    need(evidence.subject == expected, "decision subject mismatch")
    need(evidence.claim == DECISION_CLAIM, "unsupported decision claim")
    need(evidence.subject_digest == decision_digest(expected),
         "decision digest mismatch")
    checked = consume_coverage(expected.collection, evidence.coverage_evidence)
    if checked.get("status") == "unfinished":
        return checked
    rows, common, strict, regret, margins = _decision_values(
        expected, checked["rectangle"])
    need(evidence.pairwise_extrema == rows,
         "false, incomplete or reordered pairwise extrema")
    need(evidence.common_minimizers == common,
         "false complete common-minimizer set")
    need(evidence.uniformly_strict_actions == strict,
         "false uniform-strictness claim")
    need(evidence.strict_advantage_margins == margins,
         "false strict-advantage margin")
    need(evidence.named_action == expected.intended_action,
         "wrong named action")
    need(type(evidence.named_action_regret) is F and
         evidence.named_action_regret == regret,
         "false named-action regret")
    cap_met = None if expected.regret_cap is None else regret <= expected.regret_cap
    need(type(evidence.regret_cap_met) is type(cap_met) and
         evidence.regret_cap_met == cap_met, "false regret-cap result")
    return {
        "status": "checked-multistream-decision",
        "rectangle": checked["rectangle"],
        "common_minimizers": common,
        "uniformly_strict_actions": strict,
        "strict_advantage_margins": margins,
        "strictness_vacuous_for_singleton": len(expected.actions) == 1,
        "intended_action": expected.intended_action,
        "intended_action_uniformly_optimal": expected.intended_action in common,
        "intended_action_uniformly_strict": expected.intended_action in strict,
        "named_action_regret": regret,
        "regret_cap": expected.regret_cap,
        "regret_cap_met": cap_met,
        "loss_unit": expected.loss_unit,
        "risk_scope": expected.risk_scope,
        "fresh_draw_premise": expected.fresh_draw_premise,
        "coverage_alpha": expected.collection.total_alpha,
        "coverage_and_loss_not_combined": True,
    }


def classify_collection_revision(previous, current):
    previous.validate()
    current.validate()
    previous_streams = tuple((x.stream_identity, x.population_identity,
                              x.protocol_identity, x.premise)
                             for x in previous.registry)
    current_streams = tuple((x.stream_identity, x.population_identity,
                             x.protocol_identity, x.premise)
                            for x in current.registry)
    if previous_streams != current_streams or previous.rule_identity != current.rule_identity:
        return "new-collection-subject"
    if (previous.total_alpha, previous.allocations, previous.precision_bits,
            previous.joint_premise, previous.cross_stream_premise) != (
            current.total_alpha, current.allocations, current.precision_bits,
            current.joint_premise, current.cross_stream_premise):
        return "new-coverage-specification"
    same_lineage = (
        previous.record_identity == current.record_identity and
        previous.revision_identity == current.revision_identity and
        previous.predecessor_digest == current.predecessor_digest
    )
    if current.transcript == previous.transcript:
        return ("same-transcript-recalculation-no-new-evidence" if same_lineage
                else "provenance-changed-new-claim")
    if (len(current.transcript) > len(previous.transcript) and
            current.transcript[:len(previous.transcript)] == previous.transcript):
        if (current.record_identity == previous.record_identity and
                current.revision_identity != previous.revision_identity and
                current.predecessor_digest == collection_digest(previous)):
            return "append-only-transcript-extension"
        return "provenance-changed-new-claim"
    return "corrected-or-retroselected-transcript-new-claim"


def classify_decision_revision(previous, current):
    previous.validate()
    current.validate()
    collection = classify_collection_revision(previous.collection,
                                              current.collection)
    if collection != "same-transcript-recalculation-no-new-evidence":
        return collection
    if (previous.actions, previous.loss_unit, previous.intended_action,
            previous.regret_cap, previous.risk_scope,
            previous.fresh_draw_premise, previous.query) != (
            current.actions, current.loss_unit, current.intended_action,
            current.regret_cap, current.risk_scope,
            current.fresh_draw_premise, current.query):
        return "same-data-new-decision-query"
    return "same-subject-recalculation-no-new-evidence"


def wire(value):
    if isinstance(value, F):
        return str(value)
    if hasattr(value, "__dataclass_fields__"):
        return wire(asdict(value))
    if isinstance(value, dict):
        return {str(key): wire(item) for key, item in value.items()}
    if isinstance(value, (tuple, list)):
        return [wire(item) for item in value]
    return value
