"""Independent implementation check of declared uncertainty arithmetic.

Uses the retained, separately received session scores. This checks the calculation,
not exchangeability, source-parameter uncertainty or frequentist coverage in humans.
"""
import json
from pathlib import Path
import sys
import numpy as np
from scipy.stats import t
from receiver import HERE,need,close


def check_comparison(sessions,claim):
    groups=[[s['delta_brier'] for s in sessions if s['treatment']==arm] for arm in (3,4)]
    need(all(len(g)==8 for g in groups),'incorrect dependence units')
    means=[sum(g)/8 for g in groups]; point=sum(means)/2
    close(point,claim['delta_brier'],'point estimate mismatch')
    rng=np.random.default_rng(20260910); resamples=[]
    for values in groups:
        indices=rng.integers(0,8,size=(9999,8)); draws=[]
        # Independent count-vector reconstruction of each whole-session resample.
        for index in indices:
            counts=np.bincount(index,minlength=8)
            draws.append(sum(int(counts[j])*values[j] for j in range(8))/8)
        resamples.append(draws)
    pooled=sorted((x+y)/2 for x,y in zip(*resamples))
    def percentile(p):
        position=p*(len(pooled)-1); left=int(position); weight=position-left
        return pooled[left]*(1-weight)+pooled[min(left+1,len(pooled)-1)]*weight
    for actual,expected in zip(claim['bootstrap_95'],[percentile(.025),percentile(.975)]):
        close(actual,expected,'bootstrap calculation mismatch')
    components=[sum((v-m)**2 for v in g)/7/8/4 for g,m in zip(groups,means)]
    variance=sum(components); se=variance**.5
    close(se,claim['standard_error'],'standard error mismatch')
    if se:
        df=variance**2/sum(v*v/7 for v in components); close(df,claim['welch_df'],'Welch degrees mismatch')
        radius=float(t.ppf(.975,df))*se
    else: radius=0
    for actual,expected in zip(claim['welch_95'],[point-radius,point+radius]): close(actual,expected,'Welch interval mismatch')
    import math
    radius=math.sqrt(2*math.log(40)/16)
    for actual,expected in zip(claim['hoeffding_95'],[max(-1,point-radius),min(1,point+radius)]): close(actual,expected,'Hoeffding calculation mismatch')
    need(claim['bootstrap_draws']==9999,'bootstrap draw count mismatch')


def run():
    first=json.loads((HERE/'first-results/results.json').read_text())['comparisons']
    prior=json.loads((HERE/'prior-sensitivity-results.json').read_text())['shared_pure_priors']
    for value in [*first.values(),*prior.values()]: check_comparison(value['sessions'],value['comparison'])
    original=first['ten-linear']; altered=json.loads(json.dumps(original)); altered['comparison']['bootstrap_95'][0]+=.01
    try: check_comparison(altered['sessions'],altered['comparison'])
    except ValueError: rejection='false bootstrap interval rejected'
    else: raise RuntimeError('false interval accepted')
    # Exact replication projection independently generated by replication_review.py.
    exact=json.loads((HERE/'replication-review-results.json').read_text())['pooled_rounds_exact']
    retained=json.loads((HERE/'first-results/reconstruction.json').read_text())['late_first_eight_pooled_rounds']
    from fractions import Fraction
    need(len(exact)==len(retained)==32,'replication round coverage')
    for a,b in zip(exact,retained):
        need((a['treatment'],a['round'],a['n'])==(b['treatment'],b['round'],b['rows']),'replication query mismatch')
        for key,field in [('cooperation','coop'),('report','belief'),('gap','belief_minus_coop')]:
            close(float(Fraction(a[key])),b[field],'replication arithmetic mismatch')
    return {'uncertainty_comparisons_checked':len(first)+len(prior),'replication_rounds_checked':32,
        'control':rejection,'scope':'implementation conformance only; no sampling, utility, identification or coverage validation'}

if __name__=='__main__': print(json.dumps(run(),indent=2))
